# Generated by Django 2.0.6 on 2020-06-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='pic')),
                ('location', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128)),
                ('province', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'change_user',
            },
        ),
    ]
