# Generated by Django 2.0.6 on 2020-05-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.FileField(max_length=20, upload_to='')),
                ('img', models.ImageField(upload_to='pic')),
                ('upload_time', models.DateField(auto_now=True)),
                ('is_show', models.BooleanField()),
            ],
        ),
    ]
