# Generated by Django 2.0.6 on 2020-06-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.FileField(max_length=20, upload_to='')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('pulish_time', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('content', models.TextField(null=True)),
                ('img', models.ImageField(upload_to='pic')),
            ],
            options={
                'db_table': 't_Article',
            },
        ),
    ]
