# Generated by Django 2.0.6 on 2020-06-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(max_length=20, upload_to='')),
                ('grade', models.FileField(max_length=20, upload_to='')),
                ('author', models.FileField(max_length=20, upload_to='')),
                ('play_people', models.FileField(max_length=20, upload_to='')),
                ('number', models.FileField(max_length=20, upload_to='')),
                ('content', models.TextField()),
                ('pulish_time', models.DateField(auto_now=True)),
                ('ready', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 't_Album',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.FileField(max_length=20, upload_to='')),
                ('size', models.FileField(max_length=20, upload_to='')),
                ('url', models.FileField(max_length=20, upload_to='')),
                ('album_id', models.CharField(blank=True, max_length=36, null=True)),
                ('audio', models.CharField(blank=True, max_length=100, null=True)),
                ('chapter', models.ImageField(null=True, upload_to='pic')),
            ],
            options={
                'db_table': 't_chapter',
            },
        ),
    ]
