# Generated by Django 2.0.6 on 2020-06-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.FileField(max_length=20, upload_to='')),
                ('username', models.FileField(max_length=20, upload_to='')),
                ('password', models.FileField(max_length=20, upload_to='')),
                ('salt', models.TextField()),
                ('address', models.FileField(max_length=20, upload_to='')),
                ('sign', models.TextField()),
                ('picture', models.ImageField(upload_to='pic')),
                ('danger', models.BooleanField()),
                ('wait', models.FileField(max_length=20, upload_to='')),
            ],
        ),
    ]
